### ISSUE TITLE
[Bug] user settings and keystore in one go

### ISSUE THREAD

**Issue by SHolzhauer** [elastic/terraform-provider-elasticstack#329]
**Describe the bug**
When deploying a new cluster you cannot add an `xpack..security.authc.realms.oidc.*` to the keystore and elasticsearch in one go.

When you are deploying a new cluster which will need SSO you cannot do this upon creation. You will need to first deploy the cluster
and the entry in the keystore. After which a second deployment is needed to add/update the elasticsearch user settings.

**To Reproduce**
1. TF configuration used
```tf
resource "ec_deployment" "cluster" {
  name = "ec-monitoring"
  alias = "my-test"

  region                 = "eu-west-1"
  version                = "${var.cluster_version}"
  deployment_template_id = "aws-general-purpose-v4"

  elasticsearch = {
    autoscale = false
    config = {
      user_settings_yaml = file("./elastic_user_settings.yml")
    }
    
    coordinating = {
        # nu 32gb combined ingest coordinating
        size = var.memory_coordinating
        zone_count = var.zone_count
        autoscaling = {}
    }
    ml = {
        size = var.memory_ml
        zone_count = 1 #var.zone_count
        autoscaling = {}
    }
    hot = {
        size = var.memory_hot
        zone_count = var.zone_count
        autoscaling = {}
    }
    warm = {
        size = var.memory_warm
        zone_count = var.zone_count
        autoscaling = {}
    }
    cold = {
        size = var.memory_cold
        zone_count = var.zone_count
        autoscaling = {}
    }
  }

  kibana = {
    size = var.memory_kibana
    config = {
      user_settings_yaml = file("./kibana_user_settings.yml")
    }
  }
}

resource "ec_deployment_elasticsearch_keystore" "oidc_client_secret" {
  deployment_id = ec_deployment.cluster.id
  setting_name  = "xpack.security.authc.realms.oidc.realmname.rp.client_secret"
  value         = "secretvalue"
}
```
kibana_user_settings.yml
```yaml
xpack.security.authc.providers:
  oidc.oidc1:
    order: 0
    realm: realmname
    description: "Log in with SSO" 

```
elastic_user_settings.yml
```yaml
xpack:
  security:
    authc:
      realms:
        oidc:
          realmname:
            order: 2
            rp:
              response_type: code
              requested_scopes: ["email"]
              redirect_uri: "https://clusterexample.kb.eu-west-1.aws.found.io:9243/api/security/oidc/callback"
            op:
              issuer: "https://idp.example.com/"
              authorization_endpoint: "https://idp.example.com/authorize"
              token_endpoint: "https://idp.example.com/oauth/token"
              jwkset_path: "https://idp.example.com/.well-known/jwks.json"
              userinfo_endpoint: "https://idp.example.com/userinfo"
            claims:
              principal: email
```

2. TF operations to execute to get the error 'plan -> apply'
3. See the error in the output
> the elastic node(s) fail to come up as the cluster is created before the key

**Expected behavior**
Due to the dependencies this is expected, however I would expect there to be a way to do this in one go.

**Versions (please complete the following information):**
 - OS: `N/A`
 - Terraform Version ``
 - Provider version `0.7.0`
 - Elasticsearch Version `8.6.1`
